name: map_location_picker
description: Google Map location picker for flutter Based on google_maps_flutter.
version: 3.0.1
homepage: https://github.com/itsarvinddev/map_location_picker
repository: https://github.com/itsarvinddev/map_location_picker
issue_tracker: https://github.com/itsarvinddev/map_location_picker/issues
documentation: https://github.com/itsarvinddev/map_location_picker/blob/master/README.md
screenshots:
    - description: "Map Location Picker Decoded Address"
      path: assets/iphone_14_pro_1_0.png
    - description: "Map Location Picker Places autocomplete"
      path: assets/iphone_14_pro_3_2.png
    - description: "Map Location Picker dark mode"
      path: assets/iphone_14_pro_5_4.png

topics:
    - map-picker
    - location-picker
    - flutter-location-picker
    - google-maps-flutter
    - places-autocomplete

environment:
    sdk: ">=3.1.0 <4.0.0"
    flutter: ">=3.10.0"

flutter:
    plugin:
        platforms:
            android:
                default_package: google_maps_flutter_android
            ios:
                default_package: google_maps_flutter_ios
            web:
                default_package: google_maps_flutter_web

dependencies:
    flutter:
        sdk: flutter

    google_maps_flutter: ^2.12.3
    flutter_typeahead: ^5.2.0
    google_maps_apis: ^3.0.1
    geolocator: ^14.0.2
    flutter_hooks: ^0.21.2
    freezed_annotation: ^3.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    freezed: ^3.1.0
    build_runner: ^2.5.4
    lints: ^6.0.0
